services:
  # Backend
  - type: web
    name: portfolio-backend-tekeng
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: NODE_VERSION
        value: 20

  # Frontend
  - type: static
    name: portfolio-frontend-tekeng
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: portfolio-backend-tekeng
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
